version: "3.9"

services:
  missing-tree-api:
    build: .
    container_name: missing-tree-api
    ports:
      - "8000:8000"
    command: >
      uvicorn missing_tree_api.app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
