version: "3.9"

services:
  missing-tree-api:
    build: .
    container_name: missing-tree-api
    environment:
      API_KEY: 9e49fc2a-9be5-4a87-ad11-c1e488dd6df6
      AEROBOTICS_API_KEY: "" # TODO: Add Aerobotics API Key here
    ports:
      - "8000:8000"
    command: >
      uvicorn missing_tree_api.app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
